name: Run map e2e tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - warning

jobs:
  run-tests:
    name: Run tests on MacOs
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install deps
        run: pnpm i && npx playwright install
      - name: Run tests
        run: npm run test
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results
